import type { Order, Product, User } from "@/types";

export const demoUsers: User[] = [
  {
    id: "user-anaya",
    name: "Anaya Kapoor",
    email: "anaya@trendora.in",
    password: "trendora123",
    role: "user",
    joinedAt: "2025-08-12",
    avatar:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80",
    phone: "+91 98765 43210",
  },
  {
    id: "user-rihan",
    name: "Rihan Mehta",
    email: "rihan@trendora.in",
    password: "trendora123",
    role: "user",
    joinedAt: "2025-11-03",
    avatar:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80",
    phone: "+91 99887 77665",
  },
  {
    id: "admin-trendora",
    name: "Trendora Admin",
    email: "admin@trendora.in",
    password: "admin123",
    role: "admin",
    joinedAt: "2025-01-01",
    avatar:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80",
    phone: "+91 90000 11122",
  },
];

export const demoProducts: Product[] = [
  {
    id: "prod-midnight-drape",
    slug: "midnight-drape-maxi-dress",
    name: "Midnight Drape Maxi Dress",
    category: "Clothing",
    price: 2899,
    discountPrice: 2399,
    description:
      "A flowing satin-look maxi dress tailored for evening dinners, farewell parties, and elegant festive styling.",
    rating: 4.7,
    stock: 18,
    images: [
      "https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["black dress", "party wear", "maxi", "evening"],
    styleKeywords: ["party wear", "elegant", "black", "occasion"],
    colors: ["Black", "Berry"],
    sizes: ["XS", "S", "M", "L"],
    featured: true,
    trendingScore: 96,
    salesCount: 84,
    shortNote: "Statement eveningwear with fluid drape.",
    reviews: [
      {
        id: "rev-1",
        userName: "Sanya",
        rating: 5,
        comment: "Perfect for farewell night. The fabric falls beautifully.",
        date: "2026-04-15",
      },
      {
        id: "rev-2",
        userName: "Neha",
        rating: 4,
        comment: "Looks premium and comfortable for long events.",
        date: "2026-05-08",
      },
    ],
  },
  {
    id: "prod-linen-coord",
    slug: "sage-linen-co-ord-set",
    name: "Sage Linen Co-ord Set",
    category: "Clothing",
    price: 2599,
    description:
      "Relaxed tailoring with breathable texture for college presentations, brunch plans, and all-day comfort.",
    rating: 4.5,
    stock: 24,
    images: [
      "https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["co-ord", "linen", "smart casual", "workwear"],
    styleKeywords: ["casual", "minimal", "presentation", "smart casual"],
    colors: ["Sage", "Ivory"],
    sizes: ["S", "M", "L", "XL"],
    featured: true,
    trendingScore: 88,
    salesCount: 61,
    shortNote: "Polished comfort for campus-to-cafe days.",
    reviews: [
      {
        id: "rev-3",
        userName: "Aarohi",
        rating: 4,
        comment: "The color is calming and the fit feels easy.",
        date: "2026-03-22",
      },
    ],
  },
  {
    id: "prod-urban-sneaker",
    slug: "urban-cloud-sneakers",
    name: "Urban Cloud Sneakers",
    category: "Footwear",
    price: 2199,
    discountPrice: 1899,
    description:
      "Clean everyday sneakers with cushioned soles, built for commute comfort and versatile styling.",
    rating: 4.6,
    stock: 35,
    images: [
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1543508282-6319a3e2621f?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["shoes", "sneakers", "casual shoes", "white sneakers"],
    styleKeywords: ["casual shoes", "streetwear", "everyday", "college"],
    colors: ["Ivory", "Taupe"],
    sizes: ["6", "7", "8", "9", "10"],
    trendingScore: 93,
    salesCount: 110,
    shortNote: "Low-profile sneakers with everyday ease.",
    reviews: [
      {
        id: "rev-4",
        userName: "Ritika",
        rating: 5,
        comment: "Very comfortable for walking around campus.",
        date: "2026-05-11",
      },
    ],
  },
  {
    id: "prod-party-heels",
    slug: "velvet-stride-block-heels",
    name: "Velvet Stride Block Heels",
    category: "Footwear",
    price: 1799,
    description:
      "Elegant block heels that balance confidence and comfort for functions, date nights, and festive looks.",
    rating: 4.4,
    stock: 16,
    images: [
      "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1515347619252-60a4bf4fff4f?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["heels", "party wear", "occasion", "footwear"],
    styleKeywords: ["party wear", "wedding guest", "heels"],
    colors: ["Wine", "Nude"],
    sizes: ["5", "6", "7", "8"],
    trendingScore: 81,
    salesCount: 39,
    shortNote: "Dressy elevation without the discomfort.",
    reviews: [],
  },
  {
    id: "prod-tote-bag",
    slug: "atelier-structured-tote",
    name: "Atelier Structured Tote",
    category: "Bags",
    price: 1999,
    discountPrice: 1599,
    description:
      "A structured tote with spacious interiors for laptop, diary, cosmetics, and day-long essentials.",
    rating: 4.8,
    stock: 29,
    images: [
      "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["bags", "office bag", "tote", "large bag"],
    styleKeywords: ["bags under 2000", "work", "college", "everyday"],
    colors: ["Tan", "Black"],
    trendingScore: 94,
    salesCount: 102,
    shortNote: "Spacious sophistication for work and study.",
    reviews: [
      {
        id: "rev-5",
        userName: "Anjali",
        rating: 5,
        comment: "Fits my laptop and still looks chic.",
        date: "2026-04-27",
      },
    ],
  },
  {
    id: "prod-sling-bag",
    slug: "aurora-mini-sling-bag",
    name: "Aurora Mini Sling Bag",
    category: "Bags",
    price: 1299,
    description:
      "A compact sling with metallic accents, ideal for gifting, quick outings, and minimalist styling.",
    rating: 4.3,
    stock: 31,
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1559563458-527698bf5295?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["gift", "mini bag", "sling", "bags under 1500"],
    styleKeywords: ["gift for friend", "bags under 1500", "party wear"],
    colors: ["Rose Gold", "Cream"],
    trendingScore: 79,
    salesCount: 47,
    shortNote: "A compact gifting favorite with shine.",
    reviews: [],
  },
  {
    id: "prod-watch",
    slug: "luna-mesh-watch",
    name: "Luna Mesh Watch",
    category: "Accessories",
    price: 1699,
    description:
      "A refined mesh-strap watch that instantly elevates formal wear and daily outfits alike.",
    rating: 4.5,
    stock: 25,
    images: [
      "https://images.unsplash.com/photo-1523170335258-f5ed11844a49?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1434056886845-dac89ffe9b56?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["watch", "accessories", "gift", "minimal"],
    styleKeywords: ["gift for friend", "formal", "minimal"],
    colors: ["Silver", "Gold"],
    trendingScore: 86,
    salesCount: 58,
    shortNote: "Minimal polish for every outfit rotation.",
    reviews: [],
  },
  {
    id: "prod-sunglasses",
    slug: "solstice-oversized-sunglasses",
    name: "Solstice Oversized Sunglasses",
    category: "Accessories",
    price: 999,
    description:
      "Gradient-lens sunglasses with bold frames for travel looks, brunch fits, and everyday sun protection.",
    rating: 4.2,
    stock: 40,
    images: [
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1511920170033-f8396924c348?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["sunglasses", "vacation", "summer", "accessories under 1000"],
    styleKeywords: ["travel", "casual", "summer", "gift for friend"],
    colors: ["Black", "Tortoise"],
    trendingScore: 75,
    salesCount: 44,
    shortNote: "Playful statement frames for day looks.",
    reviews: [],
  },
  {
    id: "prod-serum",
    slug: "dew-lab-vitamin-c-serum",
    name: "Dew Lab Vitamin C Serum",
    category: "Beauty products",
    price: 899,
    discountPrice: 749,
    description:
      "A brightening serum designed to improve glow and support an easy beginner-friendly skincare routine.",
    rating: 4.6,
    stock: 54,
    images: [
      "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1571781565036-d3f759be73e4?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["skincare", "serum", "beauty products", "glow"],
    styleKeywords: ["skincare", "beauty products", "gift for her", "under 1000"],
    colors: ["Amber"],
    trendingScore: 92,
    salesCount: 132,
    shortNote: "Glow-boosting skincare with budget appeal.",
    reviews: [
      {
        id: "rev-6",
        userName: "Mehak",
        rating: 5,
        comment: "Lightweight and brightening without feeling sticky.",
        date: "2026-05-04",
      },
    ],
  },
  {
    id: "prod-lip-kit",
    slug: "studio-matte-lip-kit",
    name: "Studio Matte Lip Kit",
    category: "Beauty products",
    price: 1199,
    description:
      "A curated lip duo with long-wear shades that work for campus days and evening plans.",
    rating: 4.4,
    stock: 26,
    images: [
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["lipstick", "beauty kit", "gift", "makeup"],
    styleKeywords: ["gift for friend", "party wear", "beauty products"],
    colors: ["Rosewood", "Brick"],
    trendingScore: 84,
    salesCount: 69,
    shortNote: "Two modern shades for all-day confidence.",
    reviews: [],
  },
  {
    id: "prod-denim-jacket",
    slug: "retro-wash-denim-jacket",
    name: "Retro Wash Denim Jacket",
    category: "Clothing",
    price: 2499,
    description:
      "A slightly oversized denim jacket that layers well over basics and adds structure to casual fits.",
    rating: 4.5,
    stock: 21,
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1512436991641-6745cdb1723f?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["jacket", "casual", "denim", "layering"],
    styleKeywords: ["casual", "streetwear", "college", "party wear"],
    colors: ["Blue Wash"],
    sizes: ["S", "M", "L"],
    trendingScore: 83,
    salesCount: 52,
    shortNote: "Timeless layering for off-duty styling.",
    reviews: [],
  },
  {
    id: "prod-loafers",
    slug: "cityline-soft-loafers",
    name: "Cityline Soft Loafers",
    category: "Footwear",
    price: 1499,
    description:
      "Smart loafers with easy slip-on comfort, suited for office interns, meetings, and refined casual wear.",
    rating: 4.3,
    stock: 27,
    images: [
      "https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["loafers", "formal shoes", "smart casual", "shoes under 1500"],
    styleKeywords: ["formal", "shoes under 1500", "office", "casual shoes"],
    colors: ["Espresso", "Cream"],
    sizes: ["6", "7", "8", "9"],
    trendingScore: 77,
    salesCount: 41,
    shortNote: "Sharp without sacrificing comfort.",
    reviews: [],
  },
  {
    id: "prod-backpack",
    slug: "metro-tech-backpack",
    name: "Metro Tech Backpack",
    category: "Bags",
    price: 2199,
    description:
      "A laptop-ready backpack with organized pockets, sleek profile, and travel-friendly padding.",
    rating: 4.7,
    stock: 19,
    images: [
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["backpack", "college bag", "travel", "laptop bag"],
    styleKeywords: ["college", "travel", "work", "gift for brother"],
    colors: ["Slate", "Olive"],
    trendingScore: 82,
    salesCount: 36,
    shortNote: "Utility-focused design for hybrid days.",
    reviews: [],
  },
  {
    id: "prod-layer-necklace",
    slug: "starlit-layered-necklace",
    name: "Starlit Layered Necklace",
    category: "Accessories",
    price: 799,
    description:
      "A delicate layered necklace that instantly lifts basics, kurtas, and occasionwear without feeling heavy.",
    rating: 4.4,
    stock: 46,
    images: [
      "https://images.unsplash.com/photo-1617038220319-276d3cfab638?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1617038260897-41a1f14a8ca4?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["jewellery", "necklace", "gift", "party wear"],
    styleKeywords: ["party wear", "gift for friend", "under 1000"],
    colors: ["Gold"],
    trendingScore: 78,
    salesCount: 57,
    shortNote: "Light-catching detail for easy glam.",
    reviews: [],
  },
  {
    id: "prod-moisturizer",
    slug: "skin-ritual-ceramide-cream",
    name: "Skin Ritual Ceramide Cream",
    category: "Beauty products",
    price: 1099,
    description:
      "Barrier-supportive moisturizer with a rich but non-greasy finish for daily hydration and repair.",
    rating: 4.7,
    stock: 32,
    images: [
      "https://images.unsplash.com/photo-1612817288484-6f916006741a?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1556228578-8c89e6adf883?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["moisturizer", "skincare", "hydration", "beauty products"],
    styleKeywords: ["skincare", "dry skin", "beauty products", "under 1500"],
    colors: ["White"],
    trendingScore: 89,
    salesCount: 73,
    shortNote: "Daily hydration with gentle repair support.",
    reviews: [],
  },
  {
    id: "prod-kurta-set",
    slug: "amber-floral-kurta-set",
    name: "Amber Floral Kurta Set",
    category: "Clothing",
    price: 2299,
    discountPrice: 1899,
    description:
      "A festive-ready printed kurta set with graceful silhouette, made for celebrations and family gatherings.",
    rating: 4.8,
    stock: 23,
    images: [
      "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1610030469668-0b8bc79f8dfa?auto=format&fit=crop&w=1200&q=80",
    ],
    tags: ["kurta", "ethnic", "party wear", "festive"],
    styleKeywords: ["party wear", "festive", "ethnic", "gift for sister"],
    colors: ["Amber", "Ivory"],
    sizes: ["S", "M", "L", "XL"],
    featured: true,
    trendingScore: 95,
    salesCount: 90,
    shortNote: "Festive polish with easy elegance.",
    reviews: [],
  },
];

export const demoOrders: Order[] = [
  {
    id: "ord-1001",
    userId: "user-anaya",
    createdAt: "2026-01-12",
    status: "Delivered",
    paymentMethod: "UPI",
    items: [
      { productId: "prod-midnight-drape", quantity: 1, price: 2399 },
      { productId: "prod-layer-necklace", quantity: 1, price: 799 },
    ],
    shippingAddress: {
      fullName: "Anaya Kapoor",
      email: "anaya@trendora.in",
      phone: "+91 98765 43210",
      line1: "14 Green Park Road",
      city: "Indore",
      state: "Madhya Pradesh",
      zipCode: "452001",
    },
    subtotal: 3198,
    shippingFee: 99,
    discount: 200,
    total: 3097,
  },
  {
    id: "ord-1002",
    userId: "user-rihan",
    createdAt: "2026-02-18",
    status: "Delivered",
    paymentMethod: "Card",
    items: [
      { productId: "prod-urban-sneaker", quantity: 1, price: 1899 },
      { productId: "prod-backpack", quantity: 1, price: 2199 },
    ],
    shippingAddress: {
      fullName: "Rihan Mehta",
      email: "rihan@trendora.in",
      phone: "+91 99887 77665",
      line1: "72 Anand Vihar",
      city: "Jaipur",
      state: "Rajasthan",
      zipCode: "302001",
    },
    subtotal: 4098,
    shippingFee: 0,
    discount: 250,
    total: 3848,
  },
  {
    id: "ord-1003",
    userId: "user-anaya",
    createdAt: "2026-03-09",
    status: "Shipped",
    paymentMethod: "Cash on Delivery",
    items: [{ productId: "prod-serum", quantity: 2, price: 749 }],
    shippingAddress: {
      fullName: "Anaya Kapoor",
      email: "anaya@trendora.in",
      phone: "+91 98765 43210",
      line1: "14 Green Park Road",
      city: "Indore",
      state: "Madhya Pradesh",
      zipCode: "452001",
    },
    subtotal: 1498,
    shippingFee: 99,
    discount: 100,
    total: 1497,
  },
  {
    id: "ord-1004",
    userId: "user-rihan",
    createdAt: "2026-03-24",
    status: "Delivered",
    paymentMethod: "UPI",
    items: [{ productId: "prod-tote-bag", quantity: 1, price: 1599 }],
    shippingAddress: {
      fullName: "Rihan Mehta",
      email: "rihan@trendora.in",
      phone: "+91 99887 77665",
      line1: "72 Anand Vihar",
      city: "Jaipur",
      state: "Rajasthan",
      zipCode: "302001",
    },
    subtotal: 1599,
    shippingFee: 0,
    discount: 0,
    total: 1599,
  },
  {
    id: "ord-1005",
    userId: "user-anaya",
    createdAt: "2026-04-16",
    status: "Delivered",
    paymentMethod: "Card",
    items: [
      { productId: "prod-linen-coord", quantity: 1, price: 2599 },
      { productId: "prod-watch", quantity: 1, price: 1699 },
    ],
    shippingAddress: {
      fullName: "Anaya Kapoor",
      email: "anaya@trendora.in",
      phone: "+91 98765 43210",
      line1: "14 Green Park Road",
      city: "Indore",
      state: "Madhya Pradesh",
      zipCode: "452001",
    },
    subtotal: 4298,
    shippingFee: 0,
    discount: 300,
    total: 3998,
  },
  {
    id: "ord-1006",
    userId: "user-rihan",
    createdAt: "2026-05-03",
    status: "Packed",
    paymentMethod: "UPI",
    items: [
      { productId: "prod-loafers", quantity: 1, price: 1499 },
      { productId: "prod-sunglasses", quantity: 1, price: 999 },
    ],
    shippingAddress: {
      fullName: "Rihan Mehta",
      email: "rihan@trendora.in",
      phone: "+91 99887 77665",
      line1: "72 Anand Vihar",
      city: "Jaipur",
      state: "Rajasthan",
      zipCode: "302001",
    },
    subtotal: 2498,
    shippingFee: 99,
    discount: 120,
    total: 2477,
  },
];
